# -*- coding: utf-8 -*-
"""
Original Created on Tue Oct  1 15:25:40 2019
New version started at Thu Apr 30 08:30 2026
    Implement Pint Quantities to handle units

@author: mblixt
"""
import unittest

import numpy as np
import logging
import sys
import os
from typing import Callable

from bokeh.models.callbacks import CustomJS
from bokeh.models.sources import ColumnDataSource
from bokeh.models.widgets.tables import StringEditor
from dask.array.chunk import nanmin

# To test blixt_rp and blixt_utils libraries directly, without installation:
project_dir = str(os.path.dirname(__file__).replace('blixt_rp\\blixt_rp\\rp', ''))
sys.path.append(os.path.join(project_dir, 'blixt_utils'))
sys.path.append(os.path.join(project_dir, 'blixt_rp'))

import blixt_rp.rp_utils.definitions as ud
import blixt_rp.rp.rp_core as rp
from blixt_rp import Q_, ureg
from blixt_rp.core.param import Param
from blixt_utils.utils import log_table_in_smallcaps as small_log_table
from blixt_utils.utils import print_info
from blixt_rp.plotting.cross_plotter import DataSource, cnames
from blixt_rp.core.core import LogTable

logger = logging.getLogger(__name__)

# Default rock physics template constants
_rpt_kwargs = {
    'vsh': Q_(0.2, ''),         # Volume of shale, fraction
    'phi_c': Q_(0.4, ''),       # critical porosity, fraction
    'c_n': 8,                   # Coordination number in the contact cement model
    'p_conf': Q_(45, 'MPa'),    # Confining pressure in MPa (effective pressure?)
    'smcf': 0.3,                # shear modulus correction factor  (1=dry pack with perfect adhesion,
                                #   0=dry frictionless pack)
    'rho_hc': Q_(0.2, 'G/cc'),  # HC density  g/cm3
    'k_hc': Q_(0.06, 'GPa'),    # HC bulk modulus  GPa
    'rho_b': Q_(1.02, 'G/cc'),  # Brine density  g/cm3
    'k_b': Q_(2.8, 'GPa'),      # Brine bulk modulus  GPa
    'rho_qz': Q_(2.6, 'G/cc'),  # Density [g/cm3] of quartz
    'k_qz': Q_(37, 'GPa'),      # Bulk modulus GPa of quartz
    'mu_qz': Q_(45, 'GPa'),     # Shear modulus of quartz GPa
    'rho_sh': Q_(2.6, 'G/cc'),  # Density [g/cm3] of shale
    'k_sh': Q_(20, 'GPa'),      # Bulk modulus GPa of shale
    'mu_sh': Q_(10, 'GPa'),     # Shear modulus of shale GPa
    'apc': Q_(10, 'percent'),   # absolut percentage cement in percent
    'ntg': Q_(1., ''),          # Net to Gross, use the shale properties above in the non-Net
    'scheme': 2,                # scheme for calculating cement deposition
                                #   1=cement deposited at grain contacts
                                #   2=uniform layer around grains (default)
    'model': 'stiff'            # 'stiff', 'contact_cement', 'constant_cement', 'soft'

}

test_file_dir = str(os.path.dirname(__file__).replace(
    'blixt_rp\\rp',
    'test_data'))
las_fileA = os.path.join(test_file_dir, "Well A.las")

class RptVariableTable:
    def __init__(self,
                 width: int | None = None,
                 height: int | None = None):
        """

        :param width:
        :param height:
        """

        if width is None:
            width = 600
        self.width = width
        if height is None:
            height = 200
        self.height = height
        self.keys = ['variable', 'default_value', 'value', 'units']

        # Initiate an empty column data source
        self._cds = ColumnDataSource({_key: [] for _key in self.keys})

    @property
    def cds(self) -> ColumnDataSource:
        return self._cds

    def table_columns(self):
        from bokeh.models import SelectEditor, StringEditor, TableColumn
        table_columns = [
            TableColumn(field='variable', title='Variable',
                        # editor=SelectEditor(
                        #     options=list(_rpt_kwargs.keys()))
                        ),
            TableColumn(field='default_value', title='Def. Val.', editor=StringEditor()),
            TableColumn(field='value', title='Value', editor=StringEditor()),
            TableColumn(field='units', title='Units',
                        # editor=SelectEditor(
                        #     options=list(set([str(_x.units) for _x in _rpt_kwargs.values() if isinstance(_x, Q_)])))
                        )
        ]

        return table_columns

    def draw(self,
             cds: ColumnDataSource,
             rpt_lines_cds: ColumnDataSource | None = None,
             t: Q_ | None = None,
             rpt: Callable | None = None,
             constants: list | None = None,
             rpt_annotations: list | None = None
             ):
        """
        Draws the table that makes it possible to adjust the default rock physics template constants.

        :param cds:
            ColumnDataSource containing the (adjusted) RPT constants
        :param rpt_lines_cds:
            ColumnDataSource of RPT curves for display using bokeh multi_line()
            It can be generated by:
            > _vp, _vs, _rho = rpt_wrapper(phi, rpt_phi_sw, sw, return_rpt_keywords())
            > _dict = rpt_to_moduli(_vp, _vs, _rho, annotations)
            > rpt_lines_cds = ColumnDataSource(_dict)
        :param t:
            Pint Quantity with an np.array of length N
            Only used if rpt_lines_cds is not None
            t values used to draw the rock physics template, preferably less than about 10 items long for creating
            nice plots
        :param rpt:
            function
            Only used if rpt_lines_cds is not None
            Rock physics template function of t
            Should take a second argument which is used to parameterize the function
            e.g.
            def rpt(t, c, **rpt_keywords):
                return c*t + rpt_keywords.pop('zero_crossing', 0)
        :param constants:
            list
            Only used if rpt_lines_cds is not None
            list of length M of constants (pint quantities) used to parametrize the rpt function
        :param rpt_annotations:
            list
            Only used if rpt_lines_cds is not None
        :return:
        """
        from bokeh.models import DataTable, Button, Div, Select
        from bokeh.plotting import column, row

        rpt_params = list(_rpt_kwargs.keys())
        rpt_def_values = {_y: _x.magnitude if isinstance(_x, Q_) else _x for _y, _x in list(_rpt_kwargs.items())}
        # rpt_units = [str(_x.units) if isinstance(_x, Q_) else '' for _x in list(_rpt_kwargs.values())]
        rpt_units = {_y: str(_x.units) if isinstance(_x, Q_) else '' for _y, _x in list(_rpt_kwargs.items())}

        def update_table_callback():
            """
            Utilizes the changes in the default rpt keywords made in the table, and calculates new elastic properties
            based on that.
            Please note that the 'units' in the table CDS is not correctly updated for some reason, so we need to use
            default units. Shouldn't be a problem
            :return:
            """
            new_rpt_kwargs = {
                _key: (
                    Q_(_val, rpt_units[_key]) if (len(rpt_units[_key]) > 0)  else _val
                ) for _key, _val in zip(cds.data['variable'], cds.data['value'])
            }
            print('Adjusted RPT constants:')
            for _key in list(new_rpt_kwargs.keys()):
                print('  -', _key, ': ', new_rpt_kwargs[_key])

            # If provided, update the RPT curves given the new constants
            if rpt_lines_cds is not None:
                _vp, _vs, _rho = rpt_wrapper(t, rpt, constants, new_rpt_kwargs)
                _dict = rpt_to_moduli(_vp, _vs, _rho, rpt_annotations)
                rpt_lines_cds.data = _dict
                print('AI: ', _dict['ai'][0])

        def add_row_function():
            var = variable_selector.value
            new_data = dict(cds.data)

            new_data['variable'].append(var)
            new_data['value'].append(rpt_def_values[var])
            new_data['default_value'].append(rpt_def_values[var])
            new_data['units'].append(rpt_units[var])

            cds.data = new_data

        def delete_row_function():
            selected_index = cds.selected.indices
            new_data = {_x:[] for _x in self.keys}
            for _i in range(len(cds.data['variable'])):
                if _i in selected_index:
                    continue
                for _x in self.keys:
                    new_data[_x].append(cds.data[_x][_i])
            cds.selected.indices = []
            cds.data = new_data

        source_callback = CustomJS(
            # Because it is not updating the cds, this doesn't work as expected.
            # Therefor we're not using it remove it after modifying the add_row_function()?
            args=dict(source=cds, rpt_params=rpt_params, rpt_def_values=list(rpt_def_values.keys()),
                      rpt_units=list(rpt_units.keys())),
            code="""
            const data = source.data;
            const variables = rpt_params;
            const def_values = rpt_def_values;
            const units = rpt_units;
            
            // Modify the values and units to match the selected variable
            // This could potentially start an infinite loop because we modify the cds while listening to 
            // changes to it! BUT it works:-)    
            for (let i = 0; i < data['variable'].length; i++) {  // each row in the table
                console.log('Checking row ', i, 'in RPT variables');
                for (let j = 0; j < variables.length; j++) {     // each variable defined by _rpt_kwargs
                    if ( data['variable'][i] === variables[j]) {
                        console.log('  Variable ', variables[j], def_values[j], data['value'][i], units[j]);
                        data['default_value'][i] = def_values[j];  // This does not update the CDS!
                        data['units'][i] = units[j];  // This does not update the CDS!
                    }
                }
            }
            // console.log('Table is updated');
            source.data = data;
            source.change.emit();
            """
        )

        title = Div(text =
                    """
                    <div style="font-size:12px; font-weight:600; margin-bottom:0px; text-align:center">
                        Edit default RPT variables (Don't edit units!)
                    </div>
               """)

        dt = DataTable(
            source=cds,
            columns=self.table_columns(),
            editable=True,
            width=self.width,
            height=self.height,
            index_position=-1,
            index_header='index'
        )

        add_row = Button(label='Add variable', button_type='success')
        add_row.on_click(add_row_function)

        variable_selector = Select(
            title='Variable:',
            value=rpt_params[0],
            options=rpt_params
        )

        delete_row = Button(label='Delete selected rows', button_type='success')
        delete_row.on_click(delete_row_function)

        update_table = Button(label='Update', button_type='success')
        update_table.on_click(update_table_callback)

        # cds.js_on_change('patching', source_callback)

        return column(title, dt, sizing_mode='stretch_width'), add_row, variable_selector, delete_row, update_table, rpt_lines_cds


def rpt_wrapper(
        t: Q_,
        rpt: Callable,
        constants: list,
        rpt_keywords: dict
):
    """

    From plt_rpt() in plot_rp.py

    Utility function that takes a RPT (rock physics template) as input, evaluates it along one independent variable
    (t, eg. Porosity) for a specific set of rpt constants (constants, eg. list of water saturation values), to produce
    a set of Vp, Vs, Rho values (one set per item in constants) which can be drawn in a plot to illustrate the RPT

    :param t:
        Pint Quantity with an np.array of length N
        t values used to draw the rock physics template, preferably less than about 10 items long for creating
        nice plots
    :param rpt:
        function
        Rock physics template function of t
        Should take a second argument which is used to parameterize the function
        e.g.
        def rpt(t, c, **rpt_keywords):
            return c*t + rpt_keywords.pop('zero_crossing', 0)
    :param constants:
        list
        list of length M of constants (pint quantities) used to parametrize the rpt function
    :param rpt_keywords:
        dict
        Dictionary with keywords passed on to the rpt function

    :return:
        Vp, Vs, Rho
        Each is a list of Pint Quantity arrays. Each item in the list corresponds to a constant in the 'constants' input
    """
    v_p = []
    v_s = []
    rho = []

    for _c in constants:
        _v_p, _v_s, _rho = rpt(t, _c, **rpt_keywords)
        v_p.append(_v_p)
        v_s.append(_v_s)
        rho.append(_rho)

    return v_p, v_s, rho

def rpt_to_moduli(v_p: list, v_s: list, rho: list, annotations: list) -> dict:
    """
    Takes the output from rpt_wrapper (or any Vp, Vs, Density input), calculates the rock physics moduli and
    packs it into a dictionary
    :param v_p:
        list of pint Quantity arrays (or lists) of Vp.
        Each item of the list represents an array of Vp values (parameterized by e.g. porosity),
        with each item evaluated at different values of the constant (e.g. water saturation) that was used as input
        to rpt_wrapper
    :param v_s:
    :param rho:
    :param annotations:
        list of strings used to annotate the different items in the v_p list
    :return:
    """
    from blixt_rp.plotting.cross_plotter import cnames
    from blixt_rp.rp.moduli import moduli_dict
    moduli_keys = ['ai', 'vp/vs', 'mu', 'bulk', 'pr', 'lam', 'pmod', 'youngs']
    _dict = {'colors': [], 'labels': []}
    for _i, _c in enumerate(annotations):
        _moduli = moduli_dict(
            vp=v_p[_i].to('meter / second').magnitude,
            vs=v_s[_i].to('meter / second').magnitude,
            rho=rho[_i].to('kg / meter ** 3').magnitude
        )
        if _i == 0:
            for _key in moduli_keys:
                _dict[_key] = [_moduli[_key]]
        else:
            for _key in moduli_keys:
                _dict[_key].append(_moduli[_key])
        # add annotations and colors
        _dict['colors'].append(cnames[_i])
        _dict['labels'].append(annotations[_i])

    return _dict

def rpt_phi_sw(phi: Q_, sw: Q_, **kwargs):
    """
    Useful rock physics template that can return elastic properties Vp, Vs & Rho for many
    different rock physics functions (constant cement, contact cement, stiff sand, soft sand)
    from the input variables phi and sw (porosity and water saturation)

    """
    model = kwargs.pop('model', _rpt_kwargs['model'])
    phi_c = kwargs.pop('phi_c', _rpt_kwargs['phi_c'])     # critical porosity
    p_conf = kwargs.pop('p_conf', _rpt_kwargs['p_conf'])  # Confining pressure in MPa (effective pressure?)
    smcf = kwargs.pop('smcf', _rpt_kwargs['smcf'])        # shear modulus correction factor  (1=dry pack with perfect adhesion, 0=dry frictionless pack)
    rho_b = kwargs.pop('rho_b', _rpt_kwargs['rho_b'])     # Brine density  g/cm3
    k_b = kwargs.pop('k_b', _rpt_kwargs['k_b'])           # Brine bulk modulus  GPa
    rho_hc = kwargs.pop('rho_hc', _rpt_kwargs['rho_hc'])  # HC density
    k_hc = kwargs.pop('k_hc', _rpt_kwargs['k_hc'])        # HC bulk modulus
    rho_min = kwargs.pop('rho_min', None)                 # Density [g/cm3] of mineral mix
    k_min = kwargs.pop('k_min', None)                     # Bulk modulus GPa of mineral mix
    mu_min = kwargs.pop('mu_min', None)                   # Shear modulus GPa of mineral mix
    rho_qz = kwargs.pop('rho_qz', _rpt_kwargs['rho_qz'])  # Density [g/cm3] of quartz
    k_qz = kwargs.pop('k_qz', _rpt_kwargs['k_qz'])        # Bulk modulus GPa of quartz
    mu_qz = kwargs.pop('mu_qz', _rpt_kwargs['mu_qz'])     # Shear modulus of quartz
    vsh = kwargs.pop('vsh', _rpt_kwargs['vsh'])           # Volume fraction of shale
    rho_sh = kwargs.pop('rho_sh', _rpt_kwargs['rho_sh'])  # Density [g/cm3] of shale
    k_sh = kwargs.pop('k_sh', _rpt_kwargs['k_sh'])        # Bulk modulus GPa of shale
    mu_sh = kwargs.pop('mu_sh', _rpt_kwargs['mu_sh'])     # Shear modulus of shale
    ntg = kwargs.pop('ntg', _rpt_kwargs['ntg'])           # Net to Gross, use the shale properties above in the non-Net
    c_n = kwargs.pop('c_n', _rpt_kwargs['c_n'])           # Coordination number in the contact cement model
    k_cem = kwargs.pop('k_cem', _rpt_kwargs['k_qz'])      # Cement bulk modulus in GPa (quartz)
    mu_cem = kwargs.pop('mu_cem', _rpt_kwargs['mu_qz'])   # Cement shear modulus in GPa (quartz)
    scheme = kwargs.pop('scheme', _rpt_kwargs['scheme'])  # scheme for calculating cement deposition
    apc = kwargs.pop('apc', _rpt_kwargs['apc'])           # absolute percent cement (in %)
    calc_phi_eff = kwargs.pop('calc_phi_eff', False)      # set this to True to calculate effective porosity and use it

    # rp_core is not handling Pint Quantities correctly, so we need to take their magnitude
    # TODO DO THIS FOR ALL VARIABLES
    # TODO
    # Insert a test so that 'float' isn't used on the input variables that are arrays or lists
    _phi = phi.to('dimensionless').magnitude
    _sw = sw.to('dimensionless').magnitude
    _vsh = float(vsh.to('dimensionless').magnitude)
    _ntg = float(ntg.to('dimensionless').magnitude)
    _phi_c = float(phi_c.to('dimensionless').magnitude)
    _p_conf = float(p_conf.to('MPa').magnitude)
    _k_b= float(k_b.to('GPa').magnitude)
    _rho_b = float(rho_b.to('G/cc').magnitude)
    _k_hc= float(k_hc.to('GPa').magnitude)
    _rho_hc = float(rho_hc.to('G/cc').magnitude)
    _k_qz = float(k_qz.to('GPa').magnitude)
    _mu_qz = float(mu_qz.to('GPa').magnitude)
    _rho_qz = float(rho_qz.to('G/cc').magnitude)
    _k_cem = float(k_cem.to('GPa').magnitude)
    _mu_cem = float(mu_cem.to('GPa').magnitude)
    _k_sh = float(k_sh.to('GPa').magnitude)
    _mu_sh = float(mu_sh.to('GPa').magnitude)
    _rho_sh = float(rho_sh.to('G/cc').magnitude)
    _apc = float(apc.to('percent').magnitude)

    # Check if we need to calculate the average mineral properties, or if they are given
    if k_min is None:
        _k_min = rp.vrh_bounds( [_vsh, 1 - _vsh], [_k_sh, _k_qz] )[2]  # Mineral bulk modulus
    else:
        _k_min = k_min.to('GPa').magnitude

    if mu_min is None:
        _mu_min = rp.vrh_bounds( [_vsh, 1 - _vsh], [_mu_sh, _mu_qz] )[2]  # Mineral shear modulus
    else:
        _mu_min = mu_min.to('GPa').magnitude

    if rho_min is None:
        _rho_min = rp.vrh_bounds( [_vsh, 1 - _vsh], [_rho_sh, _rho_qz] )[0]  # Density of minerals
    else:
        _rho_min = rho_min.to('G/cc').magnitude

    if calc_phi_eff:
        #phi = _phi - vsh * ((rho_min - rho_sh) / (rho_min - rho_b))  # eq. 2 in https://link.springer.com/article/10.1007/s13202-020-01073-2#Fig8
        _phi = _phi * (1. - _vsh)  # eq. 1.4 in https://www.informit.com/articles/article.aspx?p=1626870&seqNum=2
    else:
        _phi = 1. * _phi

    # Apply the rock physics model to modify the mineral properties
    if model == 'stiff':
        _k_dry, _mu_dry = rp.stiffsand(
            _k_min,
            _mu_min,
            _phi,
            _phi_c,
            c_n,
            _p_conf,
            smcf)
    elif model == 'contact_cement':
        _k_dry, _mu_dry = rp.contactcement(
            _k_min,
            _mu_min,
            _phi,
            _phi_c,
            c_n,
            _k_cem,
            _mu_cem,
            scheme)
    elif model == 'constant_cement':
        _k_dry, _mu_dry = rp.constantcement(
            _k_min,
            _mu_min,
            _phi,
            _phi_c,
            _apc,
            c_n,
            _k_cem,
            _mu_cem,
            scheme,
            smcf=smcf)
    else:
        model = 'soft'
        _k_dry, _mu_dry = rp.softsand(
            _k_min,
            _mu_min,
            _phi,
            _phi_c,
            c_n,
            _p_conf,
            smcf)
    info_txt = 'Using {} rock physics template'.format(model)
    print_info(info_txt, 'info', logger)

    # Calculate the final fluid properties for the given water saturation
    print(sw, k_b, k_hc)
    _k_f2 = rp.vrh_bounds([_sw, 1.-_sw], [_k_b, _k_hc])[1]  # K_f
    _rho_f2 = rp.vrh_bounds([_sw, 1.-_sw],  [_rho_b, _rho_hc])[0]  #RHO_f

    # Use Gassman to calculate the final elastic properties
    _vp_2, _vs_2, _rho_2, _k_2 = rp.vels(_k_dry, _mu_dry, _k_min, _rho_min, _k_f2, _rho_f2, _phi)
    # # Give them units
    # vp_2 = Q_(vp_2, 'km/s')
    # vs_2 = Q_(vs_2, 'km/s')
    # rho_2 = Q_(rho_2, 'G/cc')
    # k_2 = Q_(k_2, 'GPa')

    # if ntg is not 1, the final values are modified with the harmonic mean of the Net to Gross properties
    if ntg != 1:
        _vp_2 = rp.vrh_bounds([_ntg, 1.-_ntg], [_vp_2, 1000. * rp.v_p(_k_sh, _mu_sh, _rho_sh)])[1]
        _vs_2 = rp.vrh_bounds([_ntg, 1.-_ntg], [_vs_2, 1000. * rp.v_s(_mu_sh, _rho_sh)])[1]
        _rho_2 = rp.vrh_bounds([_ntg, 1.-_ntg], [_rho_2, _rho_sh])[1]
        _k_2 = rp.vrh_bounds([_ntg, 1.-_ntg], [_k_2, _k_sh])[1]

    return Q_(_vp_2, 'm/s'), Q_(_vs_2, 'm/s'), Q_(_rho_2, 'G/cc')


def return_rpt_keywords(prev_rpt_kwargs=None, modify_keys=None, verbose=False):
    """
    Returns a default set of rock physics template keywords if prev_rpt_kwargs is set to None,
    The keywords can be modified using the dict modify_keys
    """
    if prev_rpt_kwargs is None:
        rpt_kwargs = _rpt_kwargs
    else:
        rpt_kwargs = prev_rpt_kwargs

    # modify selected keyword values
    if modify_keys is not None and isinstance(modify_keys, dict):
        for _key, _value in modify_keys.items():
            rpt_kwargs[_key] = _value

    # Determine mineral properties
    rpt_kwargs['k_min'] = Q_(
        rp.vrh_bounds(
            [rpt_kwargs['vsh'].to('dimensionless').magnitude, 1 - rpt_kwargs['vsh'].to('dimensionless').magnitude],
            [rpt_kwargs['k_sh'].to('GPa').magnitude, rpt_kwargs['k_qz'].to('GPa').magnitude]
        )[2], 'GPa')  # Mineral bulk modulus
    if verbose:
        print('k_min: {}'.format(rpt_kwargs['k_min']))
    rpt_kwargs['mu_min'] = Q_(
        rp.vrh_bounds(
            [rpt_kwargs['vsh'].to('dimensionless').magnitude, 1 - rpt_kwargs['vsh'].to('dimensionless').magnitude],
            [rpt_kwargs['mu_sh'].to('GPa').magnitude, rpt_kwargs['mu_qz'].to('GPa').magnitude]
        )[2], 'GPa')  # Mineral shear modulus
    if verbose:
        print('mu_min: {}'.format(rpt_kwargs['mu_min']))
    rpt_kwargs['rho_min'] = Q_(
        rp.vrh_bounds(
            [rpt_kwargs['vsh'].to('dimensionless').magnitude, 1 - rpt_kwargs['vsh'].to('dimensionless').magnitude],
            [rpt_kwargs['rho_sh'].to('G/cc').magnitude, rpt_kwargs['rho_qz'].to('G/cc').magnitude]
        )[0], 'G/cc')  # Density of minerals

    return rpt_kwargs

def data_source_moduli(data_source: DataSource, log_table:LogTable, verbose = False):
    """
    Takes an input data_source and adds common rock physics parameters from the Vp, Vs, Rho, data specified by the
    LogTable
    The rock physics parameters are added to the input DataSource
    :param data_source:
    :param log_table:
    :return:
    """
    from blixt_rp.rp.moduli import moduli_dict
    from blixt_rp.core.core import Template
    from numpy import nanmin, nanmax

    if log_table.multi_log:
        raise NotImplementedError('Currently we are not capable handling multi log LogTables')
    for log_type in ['P velocity', 'S velocity', 'Density']:
        if log_type not in log_table.log_types:
            raise IOError('{} is missing in LogTable {}'.format(log_type, log_table.name))
    for log_name in log_table.log_names:
        if log_name not in data_source.variables:
            raise IOError('{} is missing in DataSource {}'.format(log_name, data_source.name))

    # convert log data to to SI units:
    _vp = data_source.data[log_table['P velocity']].to('meter / second')
    _vs = data_source.data[log_table['S velocity']].to('meter / second')
    _den = data_source.data[log_table['Density']].to('kg / meter ** 3')

    moduli = moduli_dict(
        _vp.magnitude,
        _vs.magnitude,
        _den.magnitude
    )

    _key = 'ai'
    # data_source.data[_key] = moduli[_key]/1.E3 * ureg.kPa * ureg.second / ureg.meter
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='Acoustic impedance', name=_key, units='kPa s/m')

    _key = 'vp/vs'
    # data_source.data[_key] = moduli[_key] * ureg.dimensionless
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='Vp Vs ratio', name=_key, units='')

    _key = 'mu'
    # data_source.data[_key] = moduli[_key] / 1.E9 * ureg.gigaPa
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='Shear modulus', name=_key, units='GPa')

    _key = 'bulk'
    # data_source.data[_key] = moduli[_key] / 1.E9 * ureg.gigaPa
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='Bulk modulus', name=_key, units='GPa')

    _key = 'pr'
    # data_source.data[_key] = moduli[_key] * ureg.dimensionless
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='Poisson ratio', name=_key, units='')

    _key = 'lam'
    # data_source.data[_key] = moduli[_key] * 1E-9 * ureg.gigaPa
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='Lambda', name=_key, units='GPa')

    _key = 'pmod'
    # data_source.data[_key] = moduli[_key] * 1E-9 * ureg.gigaPa
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='P-wave modulus', name=_key, units='GPa')

    _key = 'youngs'
    # data_source.data[_key] = moduli[_key] * 1E-9 * ureg.gigaPa
    data_source.data[_key] = moduli[_key]
    data_source.templates[_key] = Template(full_name='Youngs modulus', name=_key, units='GPa')

    if verbose:
        print(nanmin(data_source.data[_key]), nanmax(data_source.data[_key]), data_source.templates[_key])

    # Try to modify name of DataSource if it doesn't contain the name of the LogTable used
    if log_table.name not in data_source.name:
        data_source.name = '{} {}'.format(data_source.name, log_table.name)



class TestCases(unittest.TestCase):

    def test_rpt_phi_sw(self):
        phi = Q_(0.2, ''); sw = Q_(0.1, '')
        print(rpt_phi_sw(phi, sw, **return_rpt_keywords()))
        phi = Q_(np.linspace(0.05, 0.3, 9), '')
        print(rpt_phi_sw(phi, sw, **return_rpt_keywords()))
        sw = Q_(np.linspace(0.1, 0.9, 9 ), '')
        print(rpt_phi_sw(phi, sw, **return_rpt_keywords()))

    def test_rpt_wrapper(self):
        phi = Q_(np.linspace(0.05, 0.35, 4))
        sw = [Q_(_x, '') for _x in [0.1, 0.5, 1.0]]
        v_p, v_s, rho = rpt_wrapper(phi, rpt_phi_sw, sw, return_rpt_keywords())
        for _i, _sw in enumerate(sw):
            print(_i, _sw)
            print(rho[_i])

    def test_data_source_moduli(self):
        from blixt_rp.core.well_new import Well
        from blixt_rp.core.core import LogTable
        from numpy import nanmin, nanmax
        w = Well()
        w.read_las(las_fileA, True)
        lt1 = LogTable(name='ptb5', log_table={'P velocity': 'vp_ptb5', 'S velocity': 'vs_ptb5', 'Density': 'rho_ptb5'})
        wds1 = w.data_source(log_table=lt1)
        data_source_moduli(wds1, lt1, verbose=True)
        for _key in list(wds1.keys()):
            print(_key, nanmin(wds1.data[_key]), nanmax(wds1.data[_key]))
        for _key in list(wds1.templates.keys()):
            print(_key)


    def test_rpt_to_moduli(self):
        from bokeh.plotting import figure, show
        from bokeh.models import ColumnDataSource
        from bokeh.io import output_file
        output_file(os.path.join(project_dir, 'blixt_rp\\results_folder\\plot.html'))

        phi = Q_(np.linspace(0.05, 0.35, 4))
        sw = [Q_(_x, '') for _x in [0.1, 0.5, 1.0]]
        annotations = ['SW=0.1', 'SW=0.5', 'SW=1.0']
        _vp, _vs, _rho = rpt_wrapper(phi, rpt_phi_sw, sw, return_rpt_keywords())
        _dict = rpt_to_moduli(_vp, _vs, _rho, annotations)

        source = ColumnDataSource(_dict)

        p = figure(title='Multi_Line test', width=400, height=400)
        p.multi_line(xs='ai', ys='vp/vs', line_color='colors', line_width=3, legend_field='labels', source=source)

        show(p)

    def test_rpt_table(self):
        table = RptVariableTable()
        cds = table.cds

        phi = Q_(np.linspace(0.05, 0.35, 4))
        sw = [Q_(_x, '') for _x in [0.1, 0.5, 1.0]]
        annotations = ['SW=0.1', 'SW=0.5', 'SW=1.0']
        _vp, _vs, _rho = rpt_wrapper(phi, rpt_phi_sw, sw, return_rpt_keywords())
        _dict = rpt_to_moduli(_vp, _vs, _rho, annotations)

        rpt_lines_cds = ColumnDataSource(_dict)

        return table.draw(cds, rpt_lines_cds, t=phi, rpt=rpt_phi_sw, constants=sw, rpt_annotations=annotations)